version = 0.1
[default.deploy.parameters]
stack_name = "notes-gen-ai"
resolve_s3 = true
s3_prefix = "notes-gen-ai"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
